# Generated by Django 3.2.5 on 2023-10-09 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventsite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='options',
            field=models.ManyToManyField(blank=True, choices=[('kids', 'Kid Friendly'), ('music', 'Music'), ('market', 'Market')], help_text='Tags', limit_choices_to=3, null=True, related_name='_eventsite_event_options_+', to='eventsite.Event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_day',
            field=models.DateField(blank=True, help_text='End date of the event', null=True, verbose_name='Day of the event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_day',
            field=models.DateField(help_text='Start date of the event', verbose_name='Day of the event'),
        ),
    ]
