# Generated by Django 3.2.5 on 2023-10-09 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventsite', '0002_auto_20231009_0440'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='options',
            field=models.ManyToManyField(blank=True, choices=[('kids', 'Kid Friendly'), ('music', 'Music'), ('market', 'Market')], help_text='Tags', null=True, to='eventsite.Tags'),
        ),
    ]
