# Generated by Django 3.2.5 on 2023-10-09 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventsite', '0003_auto_20231009_1828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='options',
        ),
        migrations.AddField(
            model_name='event',
            name='tag1',
            field=models.CharField(blank=True, choices=[('kids', 'Kid Friendly'), ('music', 'Music'), ('market', 'Market')], help_text='Tags', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='tag2',
            field=models.CharField(blank=True, choices=[('kids', 'Kid Friendly'), ('music', 'Music'), ('market', 'Market')], help_text='Tags', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='tag3',
            field=models.CharField(blank=True, choices=[('kids', 'Kid Friendly'), ('music', 'Music'), ('market', 'Market')], help_text='Tags', max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='Tags',
        ),
    ]
