# Generated by Django 3.2.5 on 2023-10-13 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventsite', '0004_auto_20231009_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='name',
            field=models.CharField(blank=True, help_text='Event Name', max_length=100, null=True, verbose_name='Event Name'),
        ),
        migrations.AlterField(
            model_name='event',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes', null=True, verbose_name='Textual Notes'),
        ),
    ]
