# Generated by Django 3.2.5 on 2023-10-13 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventsite', '0005_auto_20231013_0237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_day',
            field=models.DateField(blank=True, help_text='End date of the event', null=True, verbose_name='End day of the event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.TimeField(blank=True, help_text='End time', null=True, verbose_name='End time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes', null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_day',
            field=models.DateField(help_text='Start date of the event', verbose_name='Start day of the event'),
        ),
    ]
