# Generated by Django 3.2.5 on 2023-10-13 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventsite', '0006_auto_20231013_0238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(default='Event', help_text='Event Name', max_length=100, verbose_name='Event Name'),
        ),
    ]
