# Generated by Django 3.2.5 on 2023-10-17 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventsite', '0007_alter_event_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='notes',
        ),
        migrations.AddField(
            model_name='event',
            name='additional_info',
            field=models.TextField(blank=True, help_text='Additional info', null=True, verbose_name='Notes'),
        ),
    ]
