# Generated by Django 3.2.5 on 2023-10-17 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventsite', '0008_auto_20231017_0414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='additional_info',
            field=models.TextField(blank=True, help_text='Additional info', null=True, verbose_name='Additoinal Info'),
        ),
    ]
