# Generated by Django 3.2.5 on 2023-10-19 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventsite', '0009_alter_event_additional_info'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Events', 'verbose_name_plural': 'Events'},
        ),
        migrations.AddField(
            model_name='event',
            name='neighborhood',
            field=models.CharField(blank=True, choices=[('kids', 'Kid Friendly'), ('music', 'Music'), ('market', 'Market')], help_text='Neighborhood', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='tag2',
            field=models.CharField(blank=True, choices=[('union', 'Union Square'), ('david', 'Porter Square'), ('porter', 'Davis Square'), ('ball', 'Ball Square'), ('magoon', 'Magoon Square'), ('teele', 'Teele Square')], help_text='Tags', max_length=20, null=True),
        ),
    ]
