# Generated by Django 3.2.5 on 2023-10-19 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventsite', '0010_auto_20231019_0539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='neighborhood',
            field=models.CharField(blank=True, choices=[('union', 'Union Square'), ('david', 'Porter Square'), ('porter', 'Davis Square'), ('ball', 'Ball Square'), ('magoon', 'Magoon Square'), ('teele', 'Teele Square')], help_text='Neighborhood', max_length=40, null=True),
        ),
    ]
